### ISSUE TITLE
Polish App UI

### ISSUE THREAD

**Issue by brendatrieu** [brendatrieu/gymposal#37]
## ✅ Task List

- [x] Make all buttons and icons show the correct cursor.
- [x] Ensure that the user interface fluidly adapts (**mobile-first**) to:
  - [x] smartphones
  - [x] tablets
  - [x] laptops and desktops
- [x] Ensure that the user interface passes **The Wiggle Test ™️**.
- [x] Remove all "placeholders": links, buttons, and inputs that don't do anything yet.
- [x] Effectively communicate network activity and data fetching results to the user when:
  - [x] data is loading
  - [x] results are empty
  - [x] a connection error occurs
- [x] Provide the user with a pre-filled demo account (if applicable)
