### ISSUE TITLE
Refactor: Project Code Cleanup

### ISSUE THREAD

**Issue by brendatrieu** [brendatrieu/gymposal#39]
## ✅ Task List

- [x] Remove all unnecessary files and directories.
- [x] Use `lower-kebab-case` for all file and directory names.
- [x] Remove hard-coded tokens and credentials. 
- [x] Uninstall dependencies that were added but never actually used
- [x] Clean up all HTML files.
- [x] Clean up all CSS files.
- [x] Clean up all JavaScript / JSX files.
