### ISSUE TITLE
Polish Readme

### ISSUE THREAD

**Issue by brendatrieu** [brendatrieu/gymposal#41]
## ✅ Task List

- [x] Double check that my READMEs include the following sections:
  - [x] the project name
  - [x] a description
  - [x] a link to the live deployment
  - [x] 1-2 gifs
  - [x] list  of technologies used
  - [x] finished features list
  - [x] stretch features list
  - [x] system requirements (if needed)
  - [x] getting started instructions
- [x] Check all spelling and grammar.
