### ISSUE TITLE
Design Update: Navigation Bar 

### ISSUE THREAD

**Issue by brendatrieu** [brendatrieu/gymposal#53]
## ⚙️ Feature

User can toggle a menu from the navigation bar.

## 📐 Plan

Consolidate existing navigation links into a menu.

## ✅ Task List

- [x] Create a menu that can be toggled from the nav bar
- [x] Add existing links to the menu
- [x] Create a placeholder for a help or info page
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
