### ISSUE TITLE
Refactor: Penalties scheduled jobs

### ISSUE THREAD

**Issue by brendatrieu** [brendatrieu/gymposal#58]
## ✅ Task List

- [x] Break down scheduled tasks function into multiple functions
  - [x] Gather exercise data
  - [x] Determine total number of qualifying exercises
  - [x] Query for penalties
  - [x] Insert new penalties
